### ISSUE TITLE
Broken links in TOCs of the notebooks

### ISSUE THREAD

**Issue by jmichel80** [OpenBioSim/biosimspace_tutorials#1]
As observed  in [this issue](https://github.com/openmm/openmm_workshop_july2023/issues/7), clicking on links in the table of contents of the notebooks no longer works. Presumably this is a change that came from github.

See this [example](https://github.com/OpenBioSim/biosimspace_tutorials/blob/main/04_fep/01_intro_to_alchemy/alchemical_introduction.ipynb).

**Comment by lohedges** [comment]
I don't think we need to be concerned by this and don't need to make any modifications. It is only an issue if someone is viewing the notebook on GitHub and everything still works perfectly fine when using Jupyter, which is how people will interact with the tutorials. If anyone wants to view a static rendering then they should use the markdown or HTML versions. GitHub's notebook rendering engine is quite handy, but it doesn't always work as expected so can't be relied upon.

**Comment by jmichel80** [comment]
That’s ok with me
