### ISSUE TITLE
Tutorial 04: 02_RBFE 

### ISSUE THREAD

**Issue by mayank-kohli** [OpenBioSim/biosimspace_tutorials#13]
Hi, 

I was running the Tutorial 02_RBFE in 04_FEP, while I was in the scripts directory I came across the ligprep.py script in which the AMBER has been used along with the "pmemd.cuda".

As i dont have amber with me is there any other way to execute it?

**Comment by mb2055** [comment]
Hi @mayank-kohli . The script should also work with openMM, although it is untested. All you should need is to change `engine="Amber"` to `engine=OpenMM` in `runProcess` and add ` elif engine == "OpenMM": process =BSS.Process.OpenMM(system, protocol)` to this function. You will also need to remove the `amber_home` and `pmemd_path` variables if there is no amber installation on your machine.

If openMM doesn't work keep in mind that Amber is now free for all non-commercial users, and even if you don't have a GPU, sander can be used.

**Comment by mayank-kohli** [comment]
Hi, I didn't gave a try with openmm but I changed the engine to gromacs and it worked.

But I ll surely give it a try with openmm as well as amber also.
