### ISSUE TITLE
Tutorial 1: 01_introduction/03_molecular_dynamics.ipynb broken with 2023.4

### ISSUE THREAD

**Issue by jmichel80** [OpenBioSim/biosimspace_tutorials#17]
I am re-runnning all tutorials on try.openbiosim.org as part of finalising the revisions to the tutorials suite paper

The following tutorial https://github.com/OpenBioSim/biosimspace_tutorials/blob/main/01_introduction/03_molecular_dynamics.ipynb

fails with a runtime error at the last cell if the selected backend is MDTRAJ

![image](https://github.com/OpenBioSim/biosimspace_tutorials/assets/11722212/664e89c9-02b1-4930-9a28-6474a750c603)

The backends mdanalysis and sire behave as expected.

**Comment by lohedges** [comment]
Thanks, I'll take a look. There's a unit test for this, so surprising that it's failing.

**Comment by lohedges** [comment]
It works fine for me using the latest development version of the code.

![rmsd](https://github.com/OpenBioSim/biosimspace_tutorials/assets/648557/06e932e8-47a4-44fc-906a-16efec2ea766)

Note that the cell that is supposedly returning a trajectory in `mdtraj` format will need to be updated to:

```python
mdtraj = traj.getTrajectory(format="mdtraj")
```

The default has been changed to `"auto"`, which will use the first backend that works, which in this case is Sire.

**Comment by lohedges** [comment]
Looking at the history of the trajectory code I don't see any updates related to what you are seeing. It looks like the specified backend is being ignored and Sire is being used instead, e.g. it's effectively using `"auto"` rather than `"mdtraj"`. (This could be the case if the `mdtraj` install is borked for some reason.)

**Comment by jmichel80** [comment]
Very strange. I cannot reproduce the error with the code update

`mdtraj = traj.getTrajectory(format="mdtraj")`

before execution of the rmsd plot cell.
