### ISSUE TITLE
Error in protein parameterization

### ISSUE THREAD

**Issue by mayank-kohli** [OpenBioSim/biosimspace_tutorials#20]
Hi, 

While running the following command:

`prt= BSS.Parameters.ff99SBildn(prt, work_dir="tmp1").getMolecule()`

I am getting following error:

![image](https://github.com/OpenBioSim/biosimspace_tutorials/assets/64058587/f5dcaf98-0e20-4c87-9f08-21e01190a03d)

Please provide some solution to this error.

Thank you

**Comment by lohedges** [comment]
Hi,

Are you able to share the molecule that is causing the issue? It doesn't look like this is part of the tutorial suite itself. (A search for `prt` only returned this issue.) Also, it seems that you are using the Exscientia Sandpit. What happens if you just use vanilla BioSimSpace?

**Comment by lohedges** [comment]
The only time `atom0` occurs in the code is when searching for disulphide bonds. Does your molecule contain these? There are unit tests for this part of the code, though. The only thing that I can think is that the search (bonds between S elements) is returning an `Atom`, not a `Bond`.

**Comment by mayank-kohli** [comment]
Hi I updated the code and it worked.

Thank you for your help.
