### ISSUE TITLE
Funnel metadynamics error

### ISSUE THREAD

**Issue by amarye** [OpenBioSim/biosimspace_tutorials#22]
I have installed BioSimSpace as following:
conda create -n biosimspace -c conda-forge -c michellab biosimspace

When I used your tutorial, I got an error for visualisation and fun-metaD running. So could you please help me to solve it?
![Screenshot from 2024-01-16 14-36-24](https://github.com/OpenBioSim/biosimspace_tutorials/assets/55770700/96c02c4b-6a62-4dc0-aac2-2ba8135640fa)

also

![Screenshot from 2024-01-16 14-36-48](https://github.com/OpenBioSim/biosimspace_tutorials/assets/55770700/b82d63de-6a90-4060-943a-96ff77eca842)

**Comment by lohedges** [comment]
As mentioned, the code has migrated to OpenBioSim. The michellab version of the code and tutorials are only kept for reference and no longer supported. Please install the _latest_ version of BioSimSpace following the instructions [here](https://github.com/OpenBioSim/biosimspace) and try again.

Cheers.

**Comment by amarye** [comment]
It is working now. Thanks

**Comment by lohedges** [comment]
No problem. Thanks for confirming.
